---
title: "UKB - Heteroplasmy and mortality - data analysis"
subtitle: "005 - PheWAS and Pheasant analysis - Figure 8"
author: "Yun Soo Hong"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    pandoc_args: [
    "--number-sections",
    "--number-offset=0"
    ]
fontsize: 11pt
---

# Set up  

## Program description  
* This program reads in the functions (created by Vamsee) and relevant data sets to perform PheWAS and produce Figure 8. For Figure 8b (heatmap), we implement codes generated by Dan.  
  * Step 1: Read in data 
  
## Versions of R and packages  
```{r analysis_05 set up, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r analysis_05 load libraries, echo = TRUE, message = FALSE}
library(tidyverse)
library(magrittr)
library(lubridate)
library(data.table)
library(rms)
library(RColorBrewer)
library(tools)
library(splines)
library(PheWAS)
```

## Print out settings  
```{r analysis_05 print settings}
options(tibble.print_max = 100)
options(pillar.sigfig = 5)
```

# Load data  
```{r analysis_04 load data}
ukb <- readRDS("../data_cleaning/ukb_heteroplasmy_mortality_v1.rds")
phecodes <- readRDS("../../data/phewas_phesant/n502485.icd10_phecodes.rds") %>%
  as.data.frame() %>%
  mutate(
    id = as.character(id)
  )
ukb_phecode <- readRDS("../../data/phewas_phesant/n502485.ukb.data.rds")  
```

